// <auto-generated />
using System;
using KG.MES.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KG.MES.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.OperationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegacyId")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("OperationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductionOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkplaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("OperationLogs");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("CommentIds")
                        .HasColumnType("uuid[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsClaim")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEconom")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnlyPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("LegacyId")
                        .HasColumnType("text");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PlateArea")
                        .HasColumnType("numeric");

                    b.Property<int>("PlateCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReadyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WindowArea")
                        .HasColumnType("numeric");

                    b.Property<int>("WindowCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LegacyId");

                    b.HasIndex("OrderNumber");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.OrderBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegacyId")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductionOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkplaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("OrderBlocks");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.OrderFootprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegacyId")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductionOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkplaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkplaceId");

                    b.HasIndex("ProductionOrderId", "WorkplaceId")
                        .IsUnique();

                    b.ToTable("OrderFootprints");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.OrderSupply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("CommentIds")
                        .HasColumnType("uuid[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("OrderSupplies");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.ProductionOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.PrimitiveCollection<Guid[]>("CommentIds")
                        .HasColumnType("uuid[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentWorkplaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("GlazingBead")
                        .HasColumnType("text");

                    b.Property<bool>("IsTwoSidePaint")
                        .HasColumnType("boolean");

                    b.Property<string>("LegacyId")
                        .HasColumnType("text");

                    b.Property<string>("Lumber")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrentWorkplaceId");

                    b.HasIndex("LegacyId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("ProductionOrders");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LegacyId")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.SupplyCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SupplyConditions");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.SupplyItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConditionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderSupplyId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SupplyTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CommentId")
                        .IsUnique();

                    b.HasIndex("ConditionId");

                    b.HasIndex("OrderSupplyId");

                    b.HasIndex("SupplyTypeId");

                    b.HasIndex("OrderSupplyId", "SupplyTypeId")
                        .IsUnique();

                    b.ToTable("SupplyItems");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.SupplyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SupplyTypes");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LegacyId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LegacyId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.UserWorkplace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegacyId")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkplaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkplaceId");

                    b.HasIndex("UserId", "WorkplaceId")
                        .IsUnique();

                    b.ToTable("UserWorkplaces");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.Workplace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsWorkplace")
                        .HasColumnType("boolean");

                    b.Property<string>("LegacyId")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PreviousWorkplaceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LegacyId");

                    b.HasIndex("PreviousWorkplaceId");

                    b.ToTable("Workplaces");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.WorkplaceTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromWorkplaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("LegacyId")
                        .HasColumnType("text");

                    b.Property<Guid>("ToWorkplaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransitionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ToWorkplaceId");

                    b.HasIndex("FromWorkplaceId", "ToWorkplaceId")
                        .IsUnique();

                    b.ToTable("WorkplaceTransitions");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.Comment", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KG.MES.Shared.Models.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.OperationLog", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("OperationLogs")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KG.MES.Shared.Models.Entities.User", "User")
                        .WithMany("OperationLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KG.MES.Shared.Models.Entities.Workplace", "Workplace")
                        .WithMany("OperationLogs")
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionOrder");

                    b.Navigation("User");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.OrderBlock", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("OrderBlocks")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KG.MES.Shared.Models.Entities.User", "User")
                        .WithMany("OrderBlocks")
                        .HasForeignKey("UserId");

                    b.HasOne("KG.MES.Shared.Models.Entities.Workplace", "Workplace")
                        .WithMany("OrderBlocks")
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionOrder");

                    b.Navigation("User");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.OrderFootprint", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("OrderFootprints")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KG.MES.Shared.Models.Entities.Workplace", "Workplace")
                        .WithMany("OrderFootprints")
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionOrder");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.OrderSupply", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.Order", "Order")
                        .WithOne("OrderSupply")
                        .HasForeignKey("KG.MES.Shared.Models.Entities.OrderSupply", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.ProductionOrder", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.Workplace", "CurrentWorkplace")
                        .WithMany("ProductionOrders")
                        .HasForeignKey("CurrentWorkplaceId");

                    b.HasOne("KG.MES.Shared.Models.Entities.Order", "Order")
                        .WithOne("ProductionOrder")
                        .HasForeignKey("KG.MES.Shared.Models.Entities.ProductionOrder", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentWorkplace");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.SupplyItem", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.Comment", "CommentEntity")
                        .WithOne()
                        .HasForeignKey("KG.MES.Shared.Models.Entities.SupplyItem", "CommentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KG.MES.Shared.Models.Entities.SupplyCondition", "Condition")
                        .WithMany("SupplyItems")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KG.MES.Shared.Models.Entities.OrderSupply", "OrderSupply")
                        .WithMany("SupplyItems")
                        .HasForeignKey("OrderSupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KG.MES.Shared.Models.Entities.SupplyType", "SupplyType")
                        .WithMany("SupplyItems")
                        .HasForeignKey("SupplyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CommentEntity");

                    b.Navigation("Condition");

                    b.Navigation("OrderSupply");

                    b.Navigation("SupplyType");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.User", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.UserWorkplace", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.User", "User")
                        .WithMany("UserWorkplaces")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KG.MES.Shared.Models.Entities.Workplace", "Workplace")
                        .WithMany("UserWorkplaces")
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.Workplace", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.Workplace", "PreviousWorkplace")
                        .WithMany()
                        .HasForeignKey("PreviousWorkplaceId");

                    b.Navigation("PreviousWorkplace");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.WorkplaceTransition", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.Workplace", "FromWorkplace")
                        .WithMany("FromTransitions")
                        .HasForeignKey("FromWorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KG.MES.Shared.Models.Entities.Workplace", "ToWorkplace")
                        .WithMany("ToTransitions")
                        .HasForeignKey("ToWorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromWorkplace");

                    b.Navigation("ToWorkplace");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.Order", b =>
                {
                    b.Navigation("OrderSupply");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.OrderSupply", b =>
                {
                    b.Navigation("SupplyItems");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.ProductionOrder", b =>
                {
                    b.Navigation("OperationLogs");

                    b.Navigation("OrderBlocks");

                    b.Navigation("OrderFootprints");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.SupplyCondition", b =>
                {
                    b.Navigation("SupplyItems");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.SupplyType", b =>
                {
                    b.Navigation("SupplyItems");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("OperationLogs");

                    b.Navigation("OrderBlocks");

                    b.Navigation("UserWorkplaces");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.Workplace", b =>
                {
                    b.Navigation("FromTransitions");

                    b.Navigation("OperationLogs");

                    b.Navigation("OrderBlocks");

                    b.Navigation("OrderFootprints");

                    b.Navigation("ProductionOrders");

                    b.Navigation("ToTransitions");

                    b.Navigation("UserWorkplaces");
                });
#pragma warning restore 612, 618
        }
    }
}
